# 메세지 설정
messages:

  # 접두사
  prefix: "&8[&6선물함&8] &f"

  # 콘솔에서 명령어를 사용했을 때
  only_player: "&c플레이어만 사용 가능한 명령어입니다."

  # 잘못된 명령어를 사용했을 때
  wrong_command: "&c잘못된 명령어입니다."

  # 권한이 없을 때
  no_permission: "&c당신은 이 명령어를 사용할 권한이 없습니다."

  # 플레이어가 존재하지 않을 때
  player_not_found: "&c플레이어를 찾을 수 없습니다."


  # 콘피그를 리로드 했을 때
  reloaded: "&a콘피그를 성공적으로 리로드했습니다."


  # 선물함에 아이템을 보냈을 때
  sent: "&a선물함에 아이템을 보냈습니다."

  # 손에 든 아이템이 없을 때
  no_item_in_hand: "&c손에 든 아이템이 없습니다."

  # 상대의 선물함이 꽉차 있을 때
  full: "&c선물함이 꽉차 있어 선물을 보낼 수 없습니다."

  # 자신에게 선물을 보냈을 때
  cannot_send_self: "&c자신에게 선물을 보낼 수 없습니다."

  # 선물함에 아이템이 왔을 때
  received: "&a선물함에 아이템이 왔습니다!"


  # 선물함에서 아이템을 받았을 때
  receipted: "&a선물함에서 아이템을 받았습니다."

  # 수령할 수 없을 때
  cannot_receive: "&c인벤토리에 공간이 부족해 수령할 수 없습니다."


  # 모두 수령을 했으나, 선물함이 비어있을 때
  empty: "&c선물함에 아이템이 없습니다."

  # 모두 수령을 했을 때
  all_received: "&a모두 수령했습니다."


  # 도움말
  help:
    - ""
    - "&6/선물함 &8- &f선물함을 엽니다."
    - "&6/선물함 보기 <플레이어> &8- &f<플레이어>의 선물함을 엽니다."
    - "&6/선물함 보내기 <플레이어> &8- &f선물함에 아이템을 보냅니다."
    - "&6/선물함 리로드 &8- &f콘피그를 리로드합니다."
    - "&6/선물함 도움말 &8- &f해당 도움말을 봅니다."
    - ""


# 인벤토리 아이템 설정
items:

  # 모두 수령 버튼 (슬롯: 49)
  receipt_all:
    material: "END_CRYSTAL"
    amount: 1
    meta:
      displayName: "§b모두 수령"
      lores:
        - "§6모든 아이템을 수령합니다."

  # 빈칸 아이템 (슬롯: 45~48, 50~53)
  empty:
    material: "GLASS"
    amount: 1
    meta:
      displayName: "§r"