name: ST-GiftBox
main: net.starly.giftbox.GiftBoxMain
author: Starly Team
website: http://starly.kr/discord

description: GiftBox Plugin.

softdepend:
  - ST-Core

version: 1.1.1
api-version: 1.13

commands:
  giftbox:
    aliases: [ gb, 선물함 ]