name: ST-GiftBox
main: net.starly.giftbox.GiftBoxMain
author: Starly Team
website: http://starly.kr/

description: GiftBox Plugin.

softdepend:
  - ST-Core

version: 1.2.1
api-version: 1.13

commands:
  giftbox:
    aliases: [ 선물함 ]